### ISSUE TITLE
Emails going to SPAM

### ISSUE THREAD

**Issue by atulmy** [sendgrid/sendgrid-nodejs#1029]
I just tried to integrate SendGrid's Node library, and even after domain verification the emails are going to spam.

**Email:**
---
<img width="753" alt="Screenshot 2020-01-22 at 12 30 46 PM" src="https://user-images.githubusercontent.com/685786/72872554-ab8c6800-3d13-11ea-89b0-54be7a0770b6.png">

**Domain verification:**
---
<img width="514" alt="Screenshot 2020-01-22 at 12 32 29 PM" src="https://user-images.githubusercontent.com/685786/72872581-b646fd00-3d13-11ea-9165-db97464ccde1.png">

It is disappointing even after domain verification, the first ever email is going to spam.

# Technical details:
* sendgrid-nodejs version: `^6.5.0`
* node version: `v12.13.1`

**Comment by thinkingserious** [comment]
Hello @atulmy,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
