### ISSUE TITLE
Whatever I do, emails are sent immediately and not respecting the `sendAt`

### ISSUE THREAD

**Issue by JefferyHus** [sendgrid/sendgrid-nodejs#1038]
I am trying to create a scheduled email. I changed my timezone to America/New_York, then sends unix (seconds) as the `setAt` value. (I have also tried `send_at` per the documentation).

None of is respected at all, my emails are being sent the moment I request the API.

### Code Snippet
```node
      to: [
        {
          name: "John",
          email: "receiver@example.com"
        }
      ],
      from: {
        email: "test@example.com"
      },
      subject: "test",
      template_id: "",
      dynamic_template_data: {
        example: `<a href="#">example</a>`
      },
      bcc: [
        {
          email: "...."
        }
      ],
      sendAt: 1581183600
```

### Technical details:
* sendgrid-nodejs version: ^6.4.0
* node version: v12.13.1

**Comment by childish-sambino** [comment]
Just tried this and worked as expected. `sendAt` is the correct name for this library. Note that the timestamp in your example was several hours before this issue was filed so maybe it's not being generated correctly. Quick way to test the timestamp by entering it here: https://www.epochconverter.com/

**Comment by JefferyHus** [comment]
I tested the timestamp and it was correct, but still the email was being sent immediately.

**Comment by childish-sambino** [comment]
Could you post the message payload here using a future timestamp that's sending immediately?
```
console.log(JSON.stringify(Mail.create(msg), null, 2));
```

**Comment by JefferyHus** [comment]
Nothing is being logged using what you sent, but here for example the unix I send `1583496600`

**Comment by JefferyHus** [comment]
To be precise. In my settings I chose a timezone of ET, then I send a unix. So I believe in your end you are converting the timestamp I send to the timezone I have chosen in my settings.

If this is what happens, then how can I send you the timezone as a unix??

**Comment by JefferyHus** [comment]
I think i found my issue so far, but I need to understand how your backend works guys. If I send `1583496600` is is converted to UTC or to the timezone from my settings?

**Comment by childish-sambino** [comment]
I believe the value is expected to be seconds since unix epoch UTC.  The value `1583496600` is currently over 3 hours in the past.

**Comment by JefferyHus** [comment]
Ok so it's considered UTC in the end, the documentation misrepresented this, because I read that I should chose the timezone from my account settings or set the timezone using the API, then just send seconds, but instead I have to include my timezone also in the unix, this makes the API part of setting the timezone, useless in the end.

**Comment by childish-sambino** [comment]
The timezone setting does not impact the `send_at` value.

From here: https://sendgrid.com/docs/API_Reference/Web_API/timezone.html
> A user’s timezone affects the displayed dates on all Suppression Lists and Statistics.

I think it also applies to scheduled sends from the console where you're using a date picker.

Do you have a link to the docs where it's misrepresented? I've not been able to find anything.

Generally speaking, when providing a unix timestamp it is time since UTC epoch.

I see your comment here: https://github.com/sendgrid/sendgrid-ruby/issues/377#issuecomment-583781414

I'll redirect to this post.
