### ISSUE TITLE
Img src is removed when email is sent

### ISSUE THREAD

**Issue by noman-ih** [sendgrid/sendgrid-nodejs#1045]
Hi, I am facing a wired problem. I am using dynamic email. 
I can see the image in the SendGrid designer view. But when the image is sent to any Gmail address the img src is removed from it
and on hotmail the img tag is changed to this

`img data-imagetype="External" blockedimagesrc=(some source)`

**Comment by thinkingserious** [comment]
Hello @noman-ih,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
