### ISSUE TITLE
href value is shown in email.

### ISSUE THREAD

**Issue by eitheingiswe** [sendgrid/sendgrid-nodejs#1049]
### Issue Summary
While sending the email to gmail account, the link in email body is shown as a link which is correct, like that -> <a href="www.google.com">Download the License</a>

Sent a sendgrid email to **hotmail/outlookmail**, the href link in body is shown as below:
![image](https://user-images.githubusercontent.com/49706158/75661256-f2249900-5ca7-11ea-97c9-5faf7d11b06e.png)

Here is the code I sent:

![image](https://user-images.githubusercontent.com/49706158/75661939-36fcff80-5ca9-11ea-87a1-c85eb4078335.png)

### Technical details:
* sendgrid-nodejs version:6.5.1
* node version: 11.9.0

Any Help/Fix Appreciated as I've tried much time in this issue.

**Comment by thinkingserious** [comment]
Hello @eitheingiswe,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
