### ISSUE TITLE
Sending Scheduled Emails

### ISSUE THREAD

**Issue by elimence** [sendgrid/sendgrid-nodejs#106]
I am wondering if it's possible to send scheduled emails using this library.
I have looked through the docs, but haven't seen anything like that.

**Comment by dandv** [comment]
I see this API endpoint now, though I'm confused by the documentation - there's "Cancel scheduled send" but not "Schedule send" in the left sidebar:

https://sendgrid.com/docs/API_Reference/Web_API_v3/cancel_schedule_send.html

**Comment by nquinlan** [comment]
Hey @dandv! You can now schedule emails using SendGrid alone, using their [API v3](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html) or [SMTPAPI](https://sendgrid.com/docs/API_Reference/SMTP_API/scheduling_parameters.html). You can see an example of how to do this using this library in the [use cases provided](https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/time-to-send.md).

Simply, you'll add a `sendAt` parameter to the message object you're trying to send. The `sentAt` parameter should be a UNIX timestamp, since we're using Node here it's really easy to accidentally use JS timestamp in milliseconds versus seconds, so make sure you do something like `Math.round(myTime/1000)` if you're passing in a JS timevalue.

As a complete example you'd do something like this:

```js
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

const msg = {
  to: 'recipient@example.org',
  from: 'sender@example.org',
  subject: 'Hello delayed email',
  html: '<p>Some email content</p>',
  sendAt: 1500077141,
};

//ES6
sgMail
  .send(msg)
  .then(() => {}, error => {
    console.error(error);

    if (error.response) {
      console.error(error.response.body)
    }
  });
```

_A couple disclaimers: I haven't tested the above code nor have I run the SendGrid Node library in years, since I no longer work at Twilio SendGrid or maintain the library, but 99% it should work. For other folks coming to this answer in the future, my example may be out of date, but the links provided in the answer should be kept up-to-date._

**Comment by dandv** [comment]
Thanks @nquinlan, that's pretty much what I linked to :) The problem with `sendAt` is that it seems to have some [serious limitations](https://github.com/sendgrid/sendgrid-nodejs/issues/1095).
