### ISSUE TITLE
Chrome throwing "Connection Not private" when clicking on email button

### ISSUE THREAD

**Issue by tomjohnburton** [sendgrid/sendgrid-nodejs#1070]
Trying to send emails with verify button. On chrome it throws an error that my connection is not private. Any idea how I can fix this?

![image](https://user-images.githubusercontent.com/39559415/77025658-fc29e580-6991-11ea-843d-570c5f6ebbfc.png)

![image](https://user-images.githubusercontent.com/39559415/77025560-b2d99600-6991-11ea-8bea-a6fa92074d2e.png)

**Comment by thinkingserious** [comment]
Hello @tomjohnburton,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
