### ISSUE TITLE
You are not authorized to access SendGrid, please contact Support. 

### ISSUE THREAD

**Issue by lensherrggg** [sendgrid/sendgrid-nodejs#1085]
### Issue Summary
Hello, I just created a new account but when I try to log in it occurs "You are not authorized to access SendGrid, please contact Support.", and my username and password are all right.

### Steps to Reproduce
My email is gr98522@gmail.com
I could not login automatically when I finished signup process. 
And if I try to login I will get "You are not authorized to access SendGrid, please contact Support". 

### Technical details:
I tried to contact your support team but I could not get any response.

**Comment by childish-sambino** [comment]
Please see the top of the troubleshooting guide:https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md

Have you tried getting help using this form? https://support.sendgrid.com/hc/en-us/requests/new#login-issue

If so and you've still not received a response, let me know.

**Comment by thinkingserious** [comment]
Hello @lensherrggg,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by lensherrggg** [comment]
It is already solved. I got contacted from your support team yesterday and
they helped me activated my account. Thank you very much.

Elmer Thomas <notifications@github.com>于2020年4月6日 周一22:16写道：
