### ISSUE TITLE
Sending email to same domain and other domain

### ISSUE THREAD

**Issue by austinbakker** [sendgrid/sendgrid-nodejs#1108]
### Issue summary
The issue is when sending an email with sendgrid is that the email only is being sent to the email with the same domain and not the other email

### Issue Code
  const sgMail = require('@sendgrid/mail');
  sgMail.setApiKey(sendgridApi);
  const msg = {
    to: ['leads@innovativemarketing.agency', 'otherDomain@gmail.com'],
    from: 'leads@innovativemarketing.agency',
    subject: '[LEAD] nieuwe inschrijving',
    html: generateHtml(jsondata)
  };
email not being sent to 'otherDomain@gmail.com'
but is being sent to 'leads@innovativemarketing.agency',

### Steps to Reproduce
1. add same email domain as 'from'
2. send email
3. email only sent to the matching domain

### Technical details:
* sendgrid-nodejs version:
* node version:

**Comment by thinkingserious** [comment]
Hello @austinbakker,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
