### ISSUE TITLE
Using "isMultiple" with an array of emails containing "+"

### ISSUE THREAD

**Issue by DaddyWarbucks** [sendgrid/sendgrid-nodejs#1122]
### Issue Summary
I have recently begun to use the `isMultiple` flag in the mail client. I have noticed that given an array with of emails where some addresses contain "+" that the server only sends to one of those emails. 

For example
```js
// Given an array of email addresses that contain "+" such
// as gmail supports
const emails = ['bob@gmail.com', 'bob+123@gmail.com'];

// This works as expected and sends 2 emails. Bob can look in his email and see two emails
Promise.all(
  emails.map(email => {
    return sendgrid.send({ to: email, ...data });
  })
);

// This only sends one email. Bob will open his gmail and see 1 email. It may be to `bob` or
// it may be to `bob+123`, but there is only one email.
sendgrid.send({ to: emails, isMultiple: true, ...data });
```

There seems to be some kind of server side "validation" going on when using `isMultiple`. The validation does no necessarily strip the email down to just `bob@gmail.com` either. Given the email array in the example above, the email will send to either `bob@gmail` *or* `bob+123@gmail`. I have not noticed any reference to the array order on which email is used.

The "no + in emails" server validation rule may be there for good reason (I'm not sure "+" is even valid outside Gmail). But, I would like to see the "+" emails sent when using `isMultiple`.

**Comment by DaddyWarbucks** [comment]
Actually, according to the Sendgrid dashboard, the emails are delivered.

But, I still only see the one displaying in gmail? When I send the emails out individually (w/o `isMultiple`), all of the emails show up in gmail instantly. They show up in a single "thread" like UI because it is the same email to many different addresses. I would expect this to be the same with `isMultiple`. But when sending with `isMultiple` only one email is visible.

So it seems this is not a validation problem where "duplicates" are removed, but rather how they are sent to Gmail? Perhaps when using `isMultiple` the server drips the emails out more slowly and I am just not seeing them yet. 

With the dashboard showing that these emails are, in fact, delivered I realize this may just be a Gmail problem on my part. But I would have expected the emails to show in the same in my inbox (I still am only seeing one).

**Comment by childish-sambino** [comment]
I see similar behavior in my testing and consider this somewhat to be expected. Using `isMultiple` is a client-side artifact (the API knows nothing of this parameter). What it does: if the given payload contains no personalizations and contains a top-level `to` property which is an array, each email in the `to` property will be added to its own personalization. This allows each recipient to receive the email where they are the only party on the `to` line of the email. Without using `isMultiple`, all the emails in the `to` property will be sent the same email and they will each appear on the `to` line of the email.

So it's really a convenience parameter for when you don't want to go through the work of defining each personalization (or don't need to) in order to send multiple emails to multiple recipients and not have them all show up on the `to` line in the respective emails.

Now regarding plus (+) addressing: given that SendGrid does not permit the same email to be sent multiple times to the same recipient from the same API request, using plus addressing to achieve this is a bit of a hack. Now, if the content of the emails was actually different between the plus addresses, that sends fine (just tested using different dynamic template data in the same payload sent to the same email address multiple times).

All that said, I think it's best to work backwards from what you're trying to achieve. I assume the example you've given is a simplified version of what you're trying to do in order to illustrate the issue. Could you expand on what your target objective is?

**Comment by DaddyWarbucks** [comment]
Thanks for the detailed response @childish-sambino. 

I was unaware that the client created personalizations for each item in the `to` array. I have examined this code: https://github.com/sendgrid/sendgrid-nodejs/blob/9e8b91d720b2c2ffd978d130d5a97dfea0bbd62e/packages/mail/src/classes/mail-service.js#L179 and expected that `data.isMultiple` was sent to the API and that the API handled creating personalizations (or however it sent to multiple addresses). I don't see where that happens on the client?

You are right that I simplified my code above for the sake of example. But, it is exactly what I am trying to do and there is nothing to expand from a code perspective. (Note I edited my original comment code block where I had improper `email` and `emails` to `to: email` and `to: emails`). The addresses being sent to are an array of user emails. I have mainly noticed this in my local and staging environments where we developers and testers will have many user accounts where we may use `bob+account1@gmail.com` and `bob+account2@gmail.com` to be able to create many accounts.

My target objective is to send an email to multiple addresses (where the to line only contains one address) where that array of addresses may contain "duplicate" emails using the "+" sign in a single API request.

It sounds like you are onto something about the API not sending the same email content to "duplicate" addresses within the same request. And if that is the case, that is a reasonable API constraint and I can work around it client side. But, I would prefer that the API did not consider "+" addresses as duplicates. Using the "+" in emails is something I do very often as an app user.

**Comment by childish-sambino** [comment]
I understand your sentiment; it just seems like this is mainly a testing use case. In production, you wouldn't want the exact same email sent to the same address (plus addressing or otherwise) as this could lead to a poor CX. I don't see this changing on the backend side of things given that there are already restrictions against sending the same email to duplicate addresses. If you _really_ need this for testing, recommend using the first approach where you call mail send for each individual email address. There's more network overhead, but it should be reliable.

**Comment by DaddyWarbucks** [comment]
I actually would want
> exact same email sent to the same address (plus addressing ~~or otherwise~~)
because I think it leads to better CX. 

I as an app user often take advantage of the "+" to signup for accounts very often. For example, I may use `bob+github@gmail.com` and `bob+netflix@gmail.com`. This allows me to search and filter emails more easily. Furthermore, I may use `bob+netflix-billing@gmail.com` where I may create (or otherwise use) multiple emails with the same provider.

**Comment by DaddyWarbucks** [comment]
I actually would want
> exact same email sent to the same address (plus addressing ~~or otherwise~~)

because I think it leads to better CX. 

I as an app user often take advantage of the "+" to signup for accounts very often. For example, I may use `bob+github@gmail.com` and `bob+netflix@gmail.com`. This allows me to search and filter emails more easily. Furthermore, I may use `bob+netflix-billing@gmail.com` where I may create (or otherwise use) multiple emails with the same provider.

These examples may be a bit extreme, but what I am trying to say is that as a **user** I use this hack/feature often. As a **developer** I understand and appreciate why these restrictions apply and that I can work around them easily, but it would be nice if the API handled that for me. 

Thanks for the responses!

**Comment by camslice** [comment]
@DaddyWarbucks @childish-sambino I ran into this problem recently too. I agree that emails with plus addressing should be treated as unique. It's basically a way to create aliases. Email aliases would not get treated as duplicates, so plus addresses should not be treated as duplicates. Is this constraint applied by this Node SDK or at the SendGrid API level?
