### ISSUE TITLE
Why can't I log in to my account?

### ISSUE THREAD

**Issue by sinevitch** [sendgrid/sendgrid-nodejs#1124]
![image](https://user-images.githubusercontent.com/35930695/82023081-5e534e00-9696-11ea-985e-3a2370fe75c2.png)

**Comment by childish-sambino** [comment]
Did you contact support? https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md

**Comment by thinkingserious** [comment]
Hello @sinevitch,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
