### ISSUE TITLE
Segments not updated after updating contact list

### ISSUE THREAD

**Issue by camilobern** [sendgrid/sendgrid-nodejs#1129]
Hi,

I'm currently on `"@sendgrid/client": "^7.1.1"` and using the following snippet to add contacts to an existing contact list:
```
const request = { body: data, method: 'PUT', url: '/v3/marketing/contacts' };
return await sendgrid.request(request);
```
I'm getting back a 200, along with a `job_id` and after a few minutes the contact list is updated.

My issue is that a segment tied to said contact list is not being updated after the contact list has been updated. These new contacts meet the criteria specified under the segment.

I have this segment tied to a marketing campaign, which is not really sending out relevant emails due to an out-of-date segment.

**Comment by thinkingserious** [comment]
Hello @camilobern,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by crisguitar** [comment]
Did you manage to solve this? @camilobern
I am experiencing the same issue.

**Comment by camilobern** [comment]
@crisguitar I found that the time-frame for segments to reflect the latest list of contacts was not consistent. Some times it's updated almost immediate;y after the list of contacts is updated, others it would take an hour.

**Comment by sdesalas** [comment]
I've been waiting 6 hours and my segments are still not updating ⏳

**Comment by ltbittner** [comment]
I am having this issue as well. It makes segment based automation basically a useless feature. I don't want my users to have to wait multiple hours to receive a welcome email.

**Comment by childish-sambino** [comment]
Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at [support.sendgrid.com](https://support.sendgrid.com/hc/en-us).

**Comment by jakebraun** [comment]
I'm having the same issue. It doesn't look like there is a solution, except to not use the Segment feature.
