### ISSUE TITLE
 send corrupt binary and non "plain text" attachment files in email 

### ISSUE THREAD

**Issue by jaun-rg** [sendgrid/sendgrid-nodejs#1150]
### Issue Summary
When send a non plain text files (example: .zip, .pdf, ), the module respone fine, but the receive files are corrupted

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```node
return new MailMessage("test_XXXXX","pdf attachment","mail",[{
        content: await fs.readFileSync(file.zip).toString('base64'),
        filename: "file.zip",
        type: 'application/zip',
        disposition: 'attachment',
    }])
```

### Exception/Log
no exceptions or logs

### Technical details:
*   "@sendgrid/mail": "^7.2.0",
* node version: v10.21.0

### Aditional Notes
this test with png / jpeg / text plain / xml / csv are done

**Comment by thinkingserious** [comment]
Hello @jaun-rg,

Could you please provide us with an example file that is corrupted so that we may try to reproduce? If you are not comfortable posting the file here, please [open a support ticket](https://support.sendgrid.com/hc/en-us) and include it there, then respond here with your ticket number. 

I also have a similar issue [here](https://github.com/sendgrid/sendgrid-nodejs/issues/1130) but I'm also unable to reproduce that one either.

With best regards,

Elmer
