### ISSUE TITLE
authorization required while using email activity api

### ISSUE THREAD

**Issue by carveredison** [sendgrid/sendgrid-nodejs#1152]
### Issue Summary
I started with free and then purchased 30 days to access EMail Activity API but still getting - authorization required error

**Comment by thinkingserious** [comment]
Hello @carveredison,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by abdulsamadola** [comment]
Hello @carveredison, how did you get it fixed? i ran into the same error. Thanks
