### ISSUE TITLE
Mail is not sent with zip attachment

### ISSUE THREAD

**Issue by Madhu-1234** [sendgrid/sendgrid-nodejs#1184]
### Issue Summary
Mail is not sent for zip attachment. It works fine with other attachments. No error message is displayed.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```node
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey('');

const fs = require("fs");

pathToAttachment = `./TestReport.zip`;
attachment = fs.readFileSync(pathToAttachment).toString("base64");

const msg = {
  to: ['blank'],
  from: 'leaving as blank',
  subject: 'Subject',
  text: 'Sent using Node.js',
  attachments: [{
    content: attachment,
    filename: "TestReport.zip",
    type: "application/zip",
    disposition: 'attachment',
  }, ],
};
sgMail
  .send(msg)
  .then(() => {
    console.log("Email sent.");
  })
  .catch(error => {
    // Log friendly error
    console.error(error);

    if (error.response) {
      // Extract error msg
      const {message, code, response} = error;

      // Extract response msg
      const {headers, body} = response;

      console.error(body);
    }
  });
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* sendgrid-nodejs version:  "^7.2.1"

**Comment by thinkingserious** [comment]
Hello @Madhu-1234,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
