### ISSUE TITLE
Account under Review

### ISSUE THREAD

**Issue by wizzardking** [sendgrid/sendgrid-nodejs#1187]
Dear Sendgrid Team

Since about 48 hours our account is temporarily under review.
We didn't get any information about this and untill we realized it, it was allready too late. Our Customers didn't received any Mails from us. Hundreds of Tickets from our support agents never was sent to our clients and are queued. But queue will be deleted after 72h, so this is urgent.

As a Pro User, we should get support by phone and chat. Just, there isn't any phone number and Chat is offline.
So, we created a support ticket, but still no reply after 30 hours.
After 12 Hours, Live chat was online and I was able to chat with someone. But the reply was, they don't have the insight of this process and can't do anything.

I know, that this isn't the support system here - but what else can I do?

It's a good thing, that you close Spam Accounts, but we are normal sellers who send normal E-Mails with sendgrid - and pay for a service which we couldn't use.

If someone is here who did care that your company doesn't loose customers, please check the  Request #5016842 on your "support" panel.

Best Regards

**Comment by thinkingserious** [comment]
Hello @wizzardking,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
