### ISSUE TITLE
Special characters not properly escaped on dynamic template subjects

### ISSUE THREAD

**Issue by bsubedi26** [sendgrid/sendgrid-nodejs#1191]
### Issue Summary
This seems to be a similar issue to https://github.com/sendgrid/sendgrid-nodejs/issues/741. The dynamic email template subject does not properly escape special characters BUT it escapes it properly on the email body. I have attached a screenshot below:

<img width="1368" alt="Screen Shot 2020-09-04 at 10 17 09 AM" src="https://user-images.githubusercontent.com/16218026/92249587-56632800-ee98-11ea-839d-5013ab52cf1c.png">

The Subject line is: New Job Post: {{ jobTitle }}, {{{facilityName}}}

I also tried just setting the facilityName only in the subject line and it didn't escape it: {{{facilityName}}}.

Test Data:
```
{
  "facilityName": "Rockwall Golf &amp; Club",
  "jobTitle": "Golf Assistant"
}
```

Please advise if this is an issue on our end or if you need any more information.
Thanks!

### Technical details:
* sendgrid-nodejs version: latest
* node version: latest

**Comment by thinkingserious** [comment]
Hello @bsubedi26,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
