### ISSUE TITLE
Single sends with API are created as drafts

### ISSUE THREAD

**Issue by jacintofleta** [sendgrid/sendgrid-nodejs#1196]
Hello, 

I am creating single sends using the sengrid V3 api: POST /marketing/singlesends

And I'm setting the send_at parameter in the future.

My problem is my single sends are being created as drafts. And I want to actually send the emails.

Thank you in advance

**Comment by thinkingserious** [comment]
Hello @jacintofleta,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by Sledro** [comment]
same issue

@jacintofleta did you figure this out?

**Comment by rob-z** [comment]
After a lot of frustration, I found the solution to this. 

After creating the singlesend with POST /marketing/singlesends, you can send it immediately with a PUT to /marketing/singlesends/{send-id}/schedule with data: {"send_at":"now"} or a future date, of course.

**Comment by maurocasas** [comment]
Hey everyone.
I noticed this is still happening. I have tried sending the POST and the PUT after, but no luck.
Anyone has any ideas?
Appreciate it!
