### ISSUE TITLE
hideWarnings: is it a cure for a symptom and not a fix of the source?

### ISSUE THREAD

**Issue by sarahmhale** [sendgrid/sendgrid-nodejs#1205]
### Issue Summary
When sending dynamical template data such as a block of HTML code which includes ', " or &. You will have warnings if you don't use hideWarnings. But it feels like hideWarnings is a cure for a symptom and not a fix of the source. Instead of solving the problem from this PR -> https://github.com/sendgrid/sendgrid-nodejs/pull/793. hideWarnings basically hides this whole check, in this PR -> https://github.com/sendgrid/sendgrid-nodejs/pull/932

### Code Snippet
```node
    if (!this.hideWarnings) {
      Object.values(dynamicTemplateData).forEach(value => {
        if (/['"&]/.test(value)) {
          console.warn(DYNAMIC_TEMPLATE_CHAR_WARNING);
        }
      });
    }
```

### Exception/Log
```
Content with characters ', " or & may need to be escaped with three brackets
{{{ content }}}
See https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/ for more information.
```

**Comment by childish-sambino** [comment]
There isn't really a great solution without knowing what's in the template, which would require an additional network call. Given that, the warning is purely informative to users who would otherwise be unaware that triple brackets are needed in such situations. Once they have be made aware, then hiding the warning will keep the logs clean.
