### ISSUE TITLE
Emails not send with dynamic templates

### ISSUE THREAD

**Issue by samarthagarwal** [sendgrid/sendgrid-nodejs#1206]
### Issue Summary
No emails are being sent using the `send` method.

### Steps to Reproduce
1. Here is the code that I am using on a NodeJS server running on Firebase.

```
let result = await sendgridClient.send({
        to: ['sunny19071990@gmail.com','samarthagarwal@live.com'],
        from: "noreply@jesuskids.no",
        templateId: "d-e8282e44324d4c4b8740f05ae7282172",
        dynamicTemplateData: data, // complicated JSON object
})
```

2. Here is what I see in the activity section in the web app.

[https://prnt.sc/utpqah](https://prnt.sc/utpqah)

3. No emails are received.

### Exception/Log
No errors when executing the code. I get the `statusCode` 202 in the response.

### Technical details:
* sendgrid-nodejs version: ^7.2.6
* node version: 10

**Comment by thinkingserious** [comment]
Hello @samarthagarwal,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
