### ISSUE TITLE
Invalid Handlebar tags cause email not to be send, but also no error to be returned.

### ISSUE THREAD

**Issue by reckter** [sendgrid/sendgrid-nodejs#1209]
### Issue Summary
(This is more a general API-problem, but I could not find the right resource to give feedback, feel free to route this to whomever it concerns!)
When sending an email using a dynamic template with handlebars tags. If the Dynamic Template has a handlebar tag issue (because of a bold styling in it, or  missing end quotes, ...), you can not send an email using it.
Which in itself is not the issue, but I do not get any feedback when using the api, that there was an error.
Instead the email is simply not send at all, and does not even appear in the "activity" log on the sendgrid website.

### Steps to Reproduce
1. Have an email template with a broken handlebar tag in it
2. Try to send the mail

=> No error code is given but mail is not send

**Comment by thinkingserious** [comment]
Hello @reckter,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
