### ISSUE TITLE
Allow adding CC and BCC key to the email

### ISSUE THREAD

**Issue by shubhamguptaji** [sendgrid/sendgrid-nodejs#1212]
Can we allow users to add CC/BCC in the email?

**Comment by thinkingserious** [comment]
Hello @shubhamguptaji,

Yes, [here is an example](https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/cc-bcc-reply-to.md). 

With best regards,

Elmer

**Comment by shubhamguptaji** [comment]
Thanks, I searched the documentation of the package but didn't find anything. 
Can we update the README file with the above example?

**Comment by thinkingserious** [comment]
Can you please help me understand your search procedure, so that I can understand the best place to link to the example? I do see that if you search for ``cc`` or ``bcc`` as a GitHub search, the results do not link to the use cases.
 
Currently, the example I provided above, is linked from [here](https://github.com/sendgrid/sendgrid-nodejs/tree/main/packages/mail#quick-start-hello-email).

Thanks again!

**Comment by tonyh-fff** [comment]
so I noticed if I have an array of emails in "to", "cc", or "bcc" I get 500 bad request error but single emails in those fields are sent successfully

**Comment by thinkingserious** [comment]
Hello @tonyh-fff,

Please verify that were no duplicate emails across any of those arrays. Duplicate emails are not allowed. Thanks!

With best regards,

Elmer

**Comment by tonyh-fff** [comment]
> Hello @tonyh-fff,
> 
> Please verify that were no duplicate emails across any of those arrays. Duplicate emails are not allowed. Thanks!
> 
> With best regards,
> 
> Elmer

That was the issue, thanks for your help!
