### ISSUE TITLE
When I use "templateId" field "to" becomes empty in sendgrid.

### ISSUE THREAD

**Issue by AlexBychkov** [sendgrid/sendgrid-nodejs#1228]
Hello, everybody! I have weird error, when I send 
 const msg = {
    to: 'test@test.teset',
    from: 'somebody@test.test',
    subject: 'smth',
    templateId:'XXXX'
  }
I see "not delivered" in activity section, because "to" is empty, but when I replace templateid with html it sends successfully.

 const msg = {
    to: 'test@test.teset',
    from: 'somebody@test.test',
    subject: 'smth',
    html: '<strong>and easy to do anywhere, even with Node.js</strong>'
  }

What could be a problem?
Usung the latest version of library.

**Comment by JenniferMah** [comment]
Hi @AlexBychkov
Are there any other error logs you are seeing with the request? To see the full error response log follow our [trouble shooting guide](https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/success-failure-errors.md). Can you also provide which version of Node you are using so that I can try to reproduce the error you are seeing?

**Comment by AlexBychkov** [comment]
@JenniferMah Hi! Thank you for your response. No errors, so I receive 200 status. Node version is v10.16.3

**Comment by JenniferMah** [comment]
I'm unable to reproduce the errors you are seeing using Node v 10.16.3 and the latest version of the helper library. Have you already checked that your template ID is correct? Have you already set up [domain authentication](https://sendgrid.com/docs/ui/account-and-settings/how-to-set-up-domain-authentication/)?

**Comment by AlexBychkov** [comment]
Hello @JenniferMah , yes, I have configured everything, I think so that is what I send and see in sendgrid activity
![image](https://user-images.githubusercontent.com/26537920/102467020-d9337b80-4060-11eb-9e42-16594ff85936.png)
![image](https://user-images.githubusercontent.com/26537920/102467151-008a4880-4061-11eb-9d9e-0a9f31b06bcc.png)

**Comment by thinkingserious** [comment]
Hello @AlexBychkov,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
