### ISSUE TITLE
Unsubscribe groups per locale support

### ISSUE THREAD

**Issue by himanshuphirke** [sendgrid/sendgrid-nodejs#1244]
I have to send emails in English, French & Spanish.
For this I am using [Templates for Multiple language](https://github.com/sendgrid/email-templates/tree/master/dynamic-templates/different-languages)

How should I handle the Unsubscribe groups based on locale?

**Comment by shwetha-manvinkurke** [comment]
Hi @himanshuphirke, 

Are you asking where you would change the 'Unsubscribe' text based on the preferred language? 

You can find the usage guide [here](https://github.com/sendgrid/email-templates/blob/master/USAGE.md).

Thanks,
Shwetha

**Comment by shwetha-manvinkurke** [comment]
Hi @himanshuphirke, 

Are you asking where you would change the 'Unsubscribe' text based on the preferred language? 

Have you tried enclosing the module-unsubscribe div with `if/else` conditional statements?

Thanks,
Shwetha

**Comment by himanshuphirke** [comment]
Hi @shwetha-manvinkurke 
I am using %asm_group_unsubscribe_raw_url% in my Dynamic template. (Template is created using Code editor)

While sending email I pass :

 **template_id, asm: {
        group_id: asm_group_id,
        groups_to_display: [asm_group_id]
}**

So I don't want a if else in javascript code per lcoate. How can I use this at SendGrid side?

**Comment by thinkingserious** [comment]
Hello @himanshuphirke,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
