### ISSUE TITLE
403 Forbidden Access on api v3/contacdb/custom_fields

### ISSUE THREAD

**Issue by Chabelo** [sendgrid/sendgrid-nodejs#1251]
Ok, so I'm trying to get custom_fields, but i'm getting 403 status. My api key have full access over everything. You can test on "try it out" section of apis documentation:

https://sendgrid.api-docs.io/v3.0/contacts-api-custom-fields/retrieve-all-custom-fields

Thanks

**Comment by JenniferMah** [comment]
Hi @Chabelo 
I'm went ahead and removed the image showing your API key and would recommend you regenerate it since it has been exposed to the public. This GitHub page is intended to provide support for customers utilizing our `sendgrid-node` helper library. Since it does not appear you are using the helper library, I suggest you reach out to our [support team](https://support.sendgrid.com/hc/en-us) for further assistance.
