### ISSUE TITLE
Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link for EventWebhook Click Events

### ISSUE THREAD

**Issue by khaosans** [sendgrid/sendgrid-nodejs#1279]
### Issue Summary
This probably isn't a issue with node but currently using the sendgrid node library so I thought I would ask about that here.  The URL in the payload is triggering the following issue.  https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/application-gateway-crs-rulegroups-rules?tabs=owasp31#crs931-31

### Steps to Reproduce
1) Using a Web App Firewall with the rules  under request 931 from the link above. 
2) Send an email with event webhooks with click engagement events turned on.
3) Event is blocked from the endpoint and a 403 is returned.

Note: All engagement and delivery events have no issue and so they ECDSA verification does work.  

### Exception/Log
Fails our WAF layer with a 403 response
```
Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link
Mandatory rule. Cannot be disabled. Inbound Anomaly Score Exceeded (Total Inbound Score: 7 - SQLI=0,XSS=0,RFI=5,LFI=0,RCE=0,PHPI=0,HTTP=0,SESS=0): Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link
```

### Other
Would there be a work around for this issue.  Tampering with the payload just makes it harder to verify so I would prefer not to go that route.

**Comment by thinkingserious** [comment]
Hello @khaosans,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
