### ISSUE TITLE
Send single email to all contacts

### ISSUE THREAD

**Issue by jamesvclements** [sendgrid/sendgrid-nodejs#1345]
Hi there,

I've dug through the API docs and tested a few different routes but I'm stuck on this usecase.

I want to send a single email, where the content has two handlebar variables, to all the contacts.

Things I've tried:
1. I created a dynamic template, and I can send it to a manually defined list of `to` email addresses. But there's no option to send to all contacts.
  a. Exploring this route, I tried to use use the legacy API's `contactdb/recipients` endpoint to fetch all contacts and then feed that array, but received a `403 forbidden` whenever hitting the legacy endpoints.

2. I created a marketing campaign, and created a single send from the API. However, there are no options in the single send endpoint to fill in handlebar variables. Also, I can't tell if single sends created via the API will actually be send, or if the user still needs to manually approve them.

If there was some way to either send a dynamic template to all recipients, or even an endpoint to fetch all contacts, this would be an easy solve using the existing API.

**Comment by JenniferMah** [comment]
Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at [support.sendgrid.com](https://support.sendgrid.com/hc/en-us).
