### ISSUE TITLE
Trustpilot data snippet injection in Email API

### ISSUE THREAD

**Issue by bakytk** [sendgrid/sendgrid-nodejs#1346]
Hello,

So we are sending order_confirmation emails, using MJML template, 
passing `dynamic_variables, template_id` to Sendgrid Email API.

Now, we want to add Trustpilot's data snippet, that looks like this:

```
<script type="application/json+trustpilot">
    {
        "recipientName": "dynamic placeholder",
        "recipientEmail": "dynamic placeholder",
        "referenceId": "dynamic placeholder"
    }
</script>
```

It should endup in final HTML, how can we pass this?

Is it possible to add a last line like below in the MJML template ?
```
<mj-include path="../../shared/footer.mjml" />
<mj-include path="../../shared/trustpilotDataSnippet.mjml" /> 
```

**Comment by JenniferMah** [comment]
Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at [support.sendgrid.com](https://support.sendgrid.com/hc/en-us).
