### ISSUE TITLE
Sendgrid Email content is not aligned correctly in outlook application. But working in Browser view

### ISSUE THREAD

**Issue by Raju03-git** [sendgrid/sendgrid-nodejs#1348]
While Using Dynamic Templates in Sendgrid the mail contents are not displayed correctly in mail & Outlook application and it showing some warning messages at the top of the mail. Also the same outlook email content is aligned correcly when I see it from the browser. Is there anything I need to add it in code to make the content works correctly in outlook Apllication.

I have attached below images for reference. Please let me know if you want more fetails to proceed further.

Thanks in Advance,

**Image from Oulook Apllication:**

![Outlook App content-not aligned](https://user-images.githubusercontent.com/65073232/157826281-baff527f-37b8-47be-8f17-35b977e10e43.JPG)

**Image from Oulook browser View:**

![Aligned Email Content](https://user-images.githubusercontent.com/65073232/157826284-6d7e7029-a363-4f0e-ad4b-9f64599a14c0.JPG)

**Comment by childish-sambino** [comment]
Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at [support.sendgrid.com](https://support.sendgrid.com/hc/en-us).
