### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by zelliott** [sendgrid/sendgrid-nodejs#207]
I'm new to Webpack (apologies in advance for anything incorrect I say), and so not exactly sure how to proceed with this fix, but it seems is though the modules `fs`, `tls`, and `net` are unable to be resolved when bundling sendgrid with Webpack.

Has anyone else run into this problem?  If so, how did you resolve it?

**EDIT**:  Perhaps it is as easy as adding the following to the package.json?

```
  browser: {
    child_process: false
  }
```

**Comment by Mattymar** [comment]
I'm having issues with this as well.  Can't get it working with webpack, though I admit my webpack experience is also somewhat limited. I've tried to add `node: {
      fs: "empty",
      net: "empty",
      tls: "empty"
    },`

But then I get errors that fs.readFileSync is not a function, so it seems fs can't be ignored.  Then I tried to include the brfs transform in postLoaders, as was suggested for similar issues with other libraries, i.e. `postLoaders: [
        {
          include: [
            path.resolve(__dirname, 'node_modules/sendgrid/'),
            path.resolve(__dirname, 'node_modules/mime/')
          ],
          loader: 'transform?brfs'
        }
      ]`

But this left me with the error in mime.js that fs.readFileSync is not defined.  In the brfs github comments, I saw that this was because the first argument was expecting a string, so it doesn't seem brfs works in this case. 

Is there some other way to get this working?  Has anyone had success using it with webpack?

**Comment by elbuo8** [comment]
You are trying to use this module in the browser?

**Comment by Mattymar** [comment]
I didn't even consider that it wouldn't be usable in the browser.  There's a case where this would have been easier than going through my django backend, but if you're telling me it's not possible in the browser then I'll just work it out the other way.

**Comment by elbuo8** [comment]
The reality is that you could hack around enough to get it working. *But*, the problem is that your credentials will be out and exposed for anyone.

If you have a django backed, that's the preferred way to go about it :+1:

**Comment by leantorres73** [comment]
What about NodeJS server side using webpack and sendrigd? That's my case :(
