### ISSUE TITLE
Mail constructor should allow content to be an array (for HTML)

### ISSUE THREAD

**Issue by mikemaccana** [sendgrid/sendgrid-nodejs#296]
#### Issue Summary

Eg, allow this.addContent() to check for isArray() and then iterate and push each content item. Many users use both HTML and text content types and it's surprising the constructor doesn't seem to handle this. 

Sendgrid for node v2 simply had text and html fields. Sendgrid v4 does surprisingly less.

**Comment by thinkingserious** [comment]
Hi @mikemaccana,

Yes, we took a step back to decouple the library from the v2 mail send endpoint so that we can support the entire v3 web api. 

For now, in your case, I would advise you to follow the kitchen sink example: https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L15

The improvement you suggest, now on our roadmap, will be implemented here: https://github.com/sendgrid/sendgrid-nodejs/tree/master/lib/helpers/mail

If you have any other suggestions or a wish list of features, we would love to hear it :)

Thanks again for taking the time to reach out to us and provide constructive feedback. 

Please keep an eye on this repo as we'll be reaching out for feedback as we continue to iterate. If you have a bit more time, we would love your thoughts on this: https://github.com/sendgrid/sendgrid-nodejs/issues/290

Thank you!

**Comment by thinkingserious** [comment]
Hi @mikemaccana,

Please follow [this PR](https://github.com/sendgrid/sendgrid-nodejs/pull/378) for an update to this library coming soon. Your feedback would be greatly appreciated. Thanks!

With Best Regards,

Elmer
