### ISSUE TITLE
I can not send emails in php sendgrid api

### ISSUE THREAD

**Issue by ramp07860** [sendgrid/sendgrid-nodejs#341]
i got error with special character like single quotes

{"errors":[{"message":"Content-Type should be application/json.","field":null,"help":null}]}{"errors":[{"message":"Content-Type should be application/json.","field":null,"help":null}]}415

Actually i can use sendgrid api for forward rss feeds news to our friends. 

mycode here
//---------------------------------------------------------------------
function sendMail($to_array, $sub, $from, $cnt){

require 'vendor/autoload.php';
$apiKey = 'SG.xxx';
$sg = new \SendGrid($apiKey);

foreach ($to_array as $key => $emails) {
 
    $request_body = json_decode('{
      "personalizations": [
        {
          "to": [
            {
              "email": "'.$emails.'"
            }
          ],
          "subject": "'.$sub.'"
        }
      ],
      "from": {
        "email": "'.$from.'"
      },
      "content": [
        {
          "type": "text/html",
          "value": "'.mysql_real_escape_string($cnt_new).'"
        }
      ]
    }');

      $response = $sg->client->mail()->send()->post($request_body);
      echo  $res=$response->statusCode();
      echo $response->body();

}
  return $res;
}

//----------------------------------------------------------------------------------------------

**Comment by manu-silicon** [comment]
Getting the same in node.js.

**Comment by thinkingserious** [comment]
Hi @ramp07860,

Thanks for reaching out to us. I have removed the API key for your protection. You will need to create a new one.

Can you please provide some sample content so that I may try to reproduce? Thanks!

Also, you may want to re-open this issue here: https://github.com/sendgrid/sendgrid-php since this is the repo for our Node.js library.

@manu-silicon,

Could you please provide a code sample so that I may recreate this issue? Thanks!

**Comment by manu-silicon** [comment]
@thinkingserious I managed to make it work but unfortunately I did not keep the non-working code. But I think I incorrectly constructed the request by using `content` instead of `body`:

```
var request = sendgrid.emptyRequest({
    method: 'POST',
    path: '/v3/mail/send',
    body: request_body_object
});
```

**Comment by cashhcointech** [comment]
Hi,
   It's been last 5 hrs since I am looking for a solution for the same problem.

here's my code:
function sendpmail($smto, $smsub, $smbody, $smfrom,$frmpwd)
{
	require("sendgrid-php/sendgrid-php.php");

$maildet ='{
  "header":
  {
  	"Content-Type": "application/json"
  },
  "personalizations": [
    {
      "to": [
        {
          "email": "' . $smto .'"
        }
      ],
      "subject": "'. $smsub . '"
    }
  ],
  "from": {
    "email": "donotreply@kashhcoin.net",
    "name": "KashhCoin"
  },
  "content": [
    {
      "type": "text/html",
      "value": "' . $smbody . '"
    }
  ]
}';
//var_dump($maildet);
$request_body = json_decode($maildet);	
	//$apiKey = getenv('SENDGRID_API_KEY');
	$apiKey = 'SG.xxxxxxx';
	$sg = new \SendGrid($apiKey);
	
	try {
	    $response = $sg->client->mail()->send()->post($request_body);
	} catch (Exception $e) {
	    echo 'Caught exception: ',  $e->getMessage(), "\n";
	}
	echo $response->statusCode();
	echo $response->body();
	print_r($response->headers());
}


The email body:
<p >Dear XYZ,</p>
<p >
With all our heartiest congratulation,we welcome you to the 
family of&nbsp;<strong>COMPANY NAME.</strong>&nbsp;We take 
immense pleasure in sending you the welcome letter, your authorization to be 
Successful and famous. This letter confirms your registration to the world of 
prosperity and squad of team workers, also offering you unprecedented 
opportunities, financial securities, source of never ending wealth and of all 
things, peace of mind and leisure.&nbsp;<br />
<br />
Hereby we take the liberty of asking you to kindly devote some time in 
explaining your team as to how they can make their vision a certainty, so 
could you. For any further Information / assistance , please feel free to 
contact us 24 hrs at our e-mail:</p>
<p ><br />
<strong >COMPANY NAME</strong>&nbsp;family 
strives hard to make your dreams a reality and our pledge a truth. We promise 
you best of services in future and look forward a long lasting and fruitful 
association with you.<br />
<br />
<strong >Login Details:</strong></p>
<p >User Name: idname</p>
<p >Password: pwdxxx</p>
<p >Transaction Password: pwdxxx</p>
<p>
<b>
<span>
Important Note:</span></b></p>
<p>
1. You can access all 
the information related to your&nbsp;<strong >COMPANY NAME</strong><span > business 
online at our website</span><span>&nbsp;<a href=http://www.sitename.net target=_blank>www.sitename.net</a></span></p>
<p>
2. You are requested to 
update profile.</p>
<p ><br />
<br />
Best Wishes & Regards,</p>
<p>
<br />
</p>
<p>
<strong >COMPANY NAME</strong></p>

**Comment by cashhcointech** [comment]
Hi,
It's been last 5 hrs since I am looking for a solution for the same problem.

here's my code:
```
function sendpmail($smto, $smsub, $smbody, $smfrom,$frmpwd)
{
require("sendgrid-php/sendgrid-php.php");

$maildet ='{
"header":
{
"Content-Type": "application/json"
},
"personalizations": [
{
"to": [
{
"email": "' . $smto .'"
}
],
"subject": "'. $smsub . '"
}
],
"from": {
"email": "donotreply@kashhcoin.net",
"name": "KashhCoin"
},
"content": [
{
"type": "text/html",
"value": "' . $smbody . '"
}
]
}';
//var_dump($maildet);
$request_body = json_decode($maildet);
//$apiKey = getenv('SENDGRID_API_KEY');
$apiKey = 'SG.xxxxxxx';
$sg = new \SendGrid($apiKey);

try {
    $response = $sg->client->mail()->send()->post($request_body);
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}
echo $response->statusCode();
echo $response->body();
print_r($response->headers());

}
```

The email body:

```
<p >Dear XYZ,</p>
<p >
With all our heartiest congratulation,we welcome you to the 
family of&nbsp;<strong>COMPANY NAME.</strong>&nbsp;We take 
immense pleasure in sending you the welcome letter, your authorization to be 
Successful and famous. This letter confirms your registration to the world of 
prosperity and squad of team workers, also offering you unprecedented 
opportunities, financial securities, source of never ending wealth and of all 
things, peace of mind and leisure.&nbsp;<br />
<br />
Hereby we take the liberty of asking you to kindly devote some time in 
explaining your team as to how they can make their vision a certainty, so 
could you. For any further Information / assistance , please feel free to 
contact us 24 hrs at our e-mail:</p>
<p ><br />
<strong >COMPANY NAME</strong>&nbsp;family 
strives hard to make your dreams a reality and our pledge a truth. We promise 
you best of services in future and look forward a long lasting and fruitful 
association with you.<br />
<br />
<strong >Login Details:</strong></p>
<p >User Name: idname</p>
<p >Password: pwdxxx</p>
<p >Transaction Password: pwdxxx</p>
<p>
<b>
<span>
Important Note:</span></b></p>
<p>
1. You can access all 
the information related to your&nbsp;<strong >COMPANY NAME</strong><span > business 
online at our website</span><span>&nbsp;<a href=http://www.sitename.net target=_blank>www.sitename.net</a></span></p>
<p>
2. You are requested to 
update profile.</p>
<p ><br />
<br />
Best Wishes & Regards,</p>
<p>
<br />
</p>
<p>
<strong >COMPANY NAME</strong></p>
```

**Comment by thinkingserious** [comment]
Hi @cashhcointech,

Could you please provide the output of `$request_body`? Thanks!
