### ISSUE TITLE
How do you do bbc email address 

### ISSUE THREAD

**Issue by AlmogRnD** [sendgrid/sendgrid-nodejs#374]
I'm trying to set bbc but I'm not seeing this in the docs, I have tried 

var bcc_email = new helper.Email('noreply@mentorloop.com.au', 'Mentorloop'); 

which did not work and I also tried 

    var mail_settings = new helper.MailSettings()
    var bcc = new helper.Bcc(true, "noreply@mentorloop.com.au")
    var mail_settings.setBcc(bcc)

This did not work either?

**Comment by SendGridDX** [comment]
Hi @AlmogRnD,

If you are using the constructor: https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L10 (just use `addBcc` instead of `addTo`)

And if you are building the object yourself: https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L34

I hope that helps!

With Best Regards,

Elmer
