### ISSUE TITLE
[Question] Preventing receiving address from being spammed

### ISSUE THREAD

**Issue by rockchalkwushock** [sendgrid/sendgrid-nodejs#404]
I am planning on using `sendgrid` to take form data from `redux-form` and send it to my friend's email as part of her business's website. This is my first time using a mail client and I'm curious about what I can do to prevent her inbox from being spammed. My form will have built-in validation for the inputs; but I'm concerned about the form being submitted over and over again with _validated_ inputs; however, the content just being spam and not real customers. I've never worked with anything like this so maybe I'm over-thinking it? I am also curious should the data submitted be something I save on the database for x amount of time? Really unsure about all this.

**Comment by thinkingserious** [comment]
Hello @rockchalkwushock,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
