### ISSUE TITLE
No migration guide yet ?

### ISSUE THREAD

**Issue by cadesalaberry** [sendgrid/sendgrid-nodejs#431]
#### Issue Summary

As per the README, 
> v6.0.0 is a complete rewrite of this SDK for all endpoints. To upgrade from v5.X and lower, please begin here.

But the link links back to the README, it seems like no migration instructions have been written yet. Do you know when it will get updated ?

#### Steps to Reproduce

1. Checkout the README

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [01a9efe370a0e707da8d0b904209b90da8363281])

**Comment by thinkingserious** [comment]
Hello @cadesalaberry,

There is not really a direct path from v5 to v6. For example, compare the [previous](https://github.com/sendgrid/sendgrid-nodejs/tree/c29a5c4928c5875c1adfa7146efcc5149eae3d32#with-mail-helper-class) Hello Email to the [current](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#send-a-single-email-to-a-single-recipient). So my current recommendation is to rewrite your code based on the new README/USE_CASES documentation.

Obviously, I have not done a good job making that clear. Perhaps instead of 

> v6.0.0 is a complete rewrite of this SDK for all endpoints. To upgrade from v5.X and lower, please begin here.

we should say

> v6.0.0 is a complete rewrite of this SDK for all endpoints. To upgrade from v5.X and lower, we suggest you update your code based on the examples found[ here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md) for mail send and [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/USAGE.md) for all other endpoints.

If this seems unacceptable, what type of documentation were you expecting?

Thanks again for taking the time to bring this issue to light, we greatly appreciate it!

With Best Regards,

Elmer

**Comment by cadesalaberry** [comment]
Thanks Elmer !

Yes, that seems great to me, I was missing some sort of documentation of the new API, the USE_CASE is exactly what I was looking for :smile: I made a PR to update the changes accordingly (https://github.com/sendgrid/sendgrid-nodejs/pull/434)

Cheers,

PS: Btw for clarification, this sentence is in the CHANGELOG, not the README as I mentionned.
