### ISSUE TITLE
Substitution not working if the substituted data is huge 

### ISSUE THREAD

**Issue by ghost** [sendgrid/sendgrid-nodejs#508]
#### Substitution not working if the substituted data is huge 

I am trying to send **SendMultipleEmailsToMultipleRecipients** to send multiple emails to multiple recipients in batch. I don't want to personalize the email content through sendGrid's personalization since there is an in-house custom personalization process and I want to use **Substitution** to replace a template string (**{content}**) with the personalized email content. The problem is that I get badRequest once I post it.

#### Here is my code:

```
var tos = new List<SG.Helpers.Mail.EmailAddress>();
var subjects = new List<string>();
var substitutions = new List<Dictionary<string, string>>();

foreach (var message in emailMessages)
{
	tos.Add(new SG.Helpers.Mail.EmailAddress(message.To.Single(), message.ToName.Single()));
	subjects.Add(message.Subject);
	substitutions.Add(
		new Dictionary<string, string>() { { "{content}", message.Body } }
	);
}

var msg = SG.Helpers.Mail.MailHelper.CreateMultipleEmailsToMultipleRecipients(
	new SG.Helpers.Mail.EmailAddress(senderEmail, senderName),
	tos,
	subjects,
	"{content}",
	"{content}",
	substitutions
);
```

If I replace **message.Body** with let's say, **message.ToName.Single()**, the batch emails goes through successfully.

Not sure what's causing the problem or how I can approach this use-case.

#### Technical details:
* sendgrid Version: v3 (latest)

**Comment by mbernier** [comment]
There is an API limitation of 10,000 bytes for the substitutions object. Is it possible you are going past this limit? 

Also, can you please share the error string the API gives back to the library?

**Comment by thinkingserious** [comment]
Hello @Sanichita,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by mbernier** [comment]
Oops, didn't mean to close this!

**Comment by Sanichita** [comment]
Hi, thanks for the response.

The substitutions object is certainly much larger than 10k bytes and that’s because I am posting the entire email body in that.

Considering this functionality, we only have to stick to sending 1 email per person but cannot use the batch send of SendGrid the way it is.

Is there anyway we can send batch emails for our case? I understand the data transfer limitations - but if we limit the number of recipients per batch, we might find a solution.

Look forward to hearing back from you.

Thanks,
Sanaz

**Comment by ZMelo-Sendgrid** [comment]
Hi @Sanichita,

I'm really sorry that we've taken so long to get back to you. 

The best way to get around the limitation for Substitutions is to use Section Tags. Below is a link to our docs and let me know if you have other questions! 

``https://sendgrid.com/docs/API_Reference/SMTP_API/section_tags.html`` ``https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/helpers/classes/mail.d.ts#L307``

Best,
Zach M.

**Comment by BHAUTIK04** [comment]
@DrMeloMoney Thanks for the above solution. But as sendgrid has mentioned as 

> Due to low usage, this setting will be deprecated Q1 of 2020. Click here for more information.
So is there any other alternative for large substitution value (> 10000 bytes)?

**Comment by JenniferMah** [comment]
Hi @BHAUTIK04 with the depreciated of section tags we suggest you use [dynamic templates](https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/) instead to personalize your emails. If you need more help please reach out to support: [support.sendgrid.com](support.sendgrid.com)
