### ISSUE TITLE
Repo code overview documentation

### ISSUE THREAD

**Issue by nitish24p** [sendgrid/sendgrid-nodejs#608]
#### Issue Summary
This isnt a real issue, just a summary to make the repo better. How about we have a documentation explaining the overview and architecture of the repository, so that in the future if anyone wants to contribute this file can be a good starting point. 

A good example can be https://reactjs.org/docs/codebase-overview.html
This can be extremely useful

Suggestions are welcome..

I can make a PR if that's ok. Will need some guidance though.

**Comment by thinkingserious** [comment]
Hi @nitish24p,

I think this is a great idea!

The documentation you propose, should probably [go here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md#understanding-the-code-base) or in a location linked to from there. [Here](https://github.com/sendgrid/sendgrid-python/blob/master/CONTRIBUTING.md#understanding-the-code-base) is a small example from our Python repo.

I can't wait to see the PR :)

With Best Regards,

Elmer

**Comment by nitish24p** [comment]
Cool will get on it.

Also at the moment are the docs hosted anywhere? or is it only in .md files on github?

**Comment by thinkingserious** [comment]
Hi @nitish24p,

Just .md files on GitHub currently. Thanks!

**Comment by attilaaronnagy** [comment]
There was a detailed documentation about how to use this npm module when we started using this, but now I can't find it and I don't know how to send an attachment... Is there an .md file or url somewhere?

**Comment by thinkingserious** [comment]
HI @attilaaronnagy,

I believe [this](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#attachments) might be what you are looking for.

Thanks!

With Best Regards,

Elmer

**Comment by attilaaronnagy** [comment]
Awesome!! Thanks a lot!

**Comment by thinkingserious** [comment]
Thanks for the follow up @attilaaronnagy!

For the sake of improving the experience for those that follow, I would love to understand how we can make that documentation more obvious.

Could you please describe the steps you took when you could not find that documentation? For example, what pages did you look at? Did you reach out to our support team?

Thank you!

With Best Regards,

Elmer

**Comment by attilaaronnagy** [comment]
I think my biggest problem was that last time when I used this repo it was way simpler and now when I came back I did not read all of the readme-s from top to bottom. I thought just by quickly clicking around I can find it.

On the first page I think the table of contents should have a separate section like "packages" or "options" where I would list them and I would make that part the most prominent. This is the part that 99% of the developers need and it's currently under ".env file" header. And i would make the list more like this (so from a first blink I can decide what I need):

----

## Packages

### Just sending email
@sendgrid/mail
### All other SendGrid v3 Web API endpoints
@sendgrid/client

----

Also in the sendgrid/mail I did never find this line "For more complex use cases, please see USE_CASES.md." because I never looked for it under "quick start". I think it should be under a separate header like:

----

## Complex use cases
Please see USE_CASES.md.

**Comment by thinkingserious** [comment]
Thanks for taking the time to provide additional feedback! 

That .env file header should not have been there, I have removed it. I hope this clarification helps.
