### ISSUE TITLE
Getting email info from x-message-id

### ISSUE THREAD

**Issue by natcohen** [sendgrid/sendgrid-nodejs#617]
I'm trying to find a way to get email's status with its `x-message-id`.

Is there a way to send the `x-message-id` and get if an email was successfully sent, opened and link clicked? Information we can see on the dashboard...

**Comment by thinkingserious** [comment]
Hello @natcohen,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by fahadrokomari** [comment]
@natcohen Did you get the solution?

**Comment by thinkingserious** [comment]
Hi @fahadrokomari,

I recommend you reach out to our [support team](https://support.sendgrid.com) also. Thanks!

With Best Regards,

Elmer

**Comment by fahadrokomari** [comment]
@thinkingserious Thank you.
