### ISSUE TITLE
When receiving a 401 response cannot save error as json

### ISSUE THREAD

**Issue by warnero** [sendgrid/sendgrid-nodejs#626]
#### Issue Summary
If I accidentally send the wrong api key I get back a 401. Unfortunately when I try and save this for logging purposes I get an error. (Note the string below is output from the 
```
console.error('catching error', error.message, error.code, error.response);
                    
12:46:41 PM web.1 |  catching error Unauthorized 401 { headers:
12:46:41 PM web.1 |     { server: 'nginx',
12:46:41 PM web.1 |       date: 'Tue, 21 Nov 2017 18:46:39 GMT',
12:46:41 PM web.1 |       'content-type': 'application/json',
12:46:41 PM web.1 |       'content-length': '116',
12:46:41 PM web.1 |       connection: 'close',
12:46:41 PM web.1 |       'access-control-allow-origin': 'https://sendgrid.api-docs.io',
12:46:41 PM web.1 |       'access-control-allow-methods': 'POST',
12:46:41 PM web.1 |       'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
12:46:41 PM web.1 |       'access-control-max-age': '600',
12:46:41 PM web.1 |       'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' },
12:46:41 PM web.1 |    body: undefined }
12:46:41 PM web.1 |  error sending email TypeError: Cannot read property 'errors' of undefined
12:46:41 PM web.1 |      at ResponseError.toString (/Users/warner/code/goto10/paperless-web/node_modules/@sendgrid/helpers/classes/response-error.js:45:27)
```

#### Steps to Reproduce

1. Put in incorrect key
2. Try and save response to json document
3. Get error

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-nodejs Version: 6.1.4
* Node.js Version: 6.11.5

**Comment by nitish24p** [comment]
Do you mean something like this
```javascript
const fs = require('fs');
const sgMail = require('@sendgrid/mail');

sgMail.setApiKey(API_KEY);
const msg = {
  to: 'email@xyz.com;email@abc.com',
  from: 'test@example.com',
  subject: 'Sending with SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
  html: '<strong>and easy to do anywhere, even with Node.js</strong>',
};
sgMail.send(msg)
  .then(success => console.log(success))
  .catch(error => {
    fs.writeFileSync('error.json', JSON.stringify(error.response.body));
  });
```

**Comment by warnero** [comment]
It looks like the `body: undefined` in the log is probably what is causing the problem. I'm working around it already but I figured that you all would want to fix the internals and make sure you don't try and call a toString on a variable that doesn't exist.

**Comment by nitish24p** [comment]
So the success block returns an array, where as the catch block returns an object. ☹️ . Also the sendMail post api doesn't return any json when a mail is send i did a console log in the client js
```javascript
request(data, cb) {

    //Create request
    const request = this.createRequest(data);

    //Perform request
    const promise = new Promise((resolve, reject) => {
      http(request, (error, response, body) => {
        console.log(body)
        if (error) {
          return reject(error);
        }

        //Response error
        if (response.statusCode >= 400) {
          return reject(new ResponseError(response));
        }

        //Successful response
        resolve([response, body]);
      });
    });
```
and ended up getting an undefined for a 201 case. The error block is working fine.
@adamreisnz  @thinkingserious any particular reason for the above case?

**Comment by adamreisnz** [comment]
The REST client is built around the [request](https://www.npmjs.com/package/request) library. A successful response is returned [as an array](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/src/client.js#L128) so that you can access and interrogate the response, as well as have direct access to the JSON response body. Basically we just pass on what is [returned from request](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/src/client.js#L115).

If there is a request error, e.g. something wrong with the request, then we just [return that error as is](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/src/client.js#L119).

If there is a response error, e.g. an error response from the API, then we [convert it](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/src/client.js#L124) to a [ResponseError](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/helpers/classes/response-error.js).

Neither error type should be saved into a database as is. Response errors have helpers to convert them [to a String](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/helpers/classes/response-error.js#L42) or [to JSON](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/helpers/classes/response-error.js#L59).

So I Imagine you'd want to save the output of `error.toJSON()` into your database.

Please let me know if anything else is unclear.

**Comment by thinkingserious** [comment]
Thanks for jumping in to help @adamreisnz!

@nitish24p,

Were you able to resolve your issue?

With Best Regards,

Elmer
