### ISSUE TITLE
@sendgrid/mail installs client libraries too

### ISSUE THREAD

**Issue by danielpspring** [sendgrid/sendgrid-nodejs#648]
#### Issue Summary

According to the documentation one can install @sendgrid/mail and @sendgrid/client separately. However, when installing @sendgrid/mail it is also installing @sendgrid/client. Is this necessary? I'm trying to reduce my app size to 5MB and the @sendgrid install is quite large pushing me over my limit. 

#### Steps to Reproduce

1. npm install @sendgrid/mail --save

**Comment by thinkingserious** [comment]
Hello @danielpspring,

With regards to our documentation, I believe you are referring to this: "This library is broken up into several packages as a monorepo so that you only need to install the packages necessary for your use case." This is true, we will only install what is necessary and in the case of @sendgrid/mail, it needs @sendgrid/client and @sendgrid/helpers. 

The main thing we were trying to achieve with the monorepo, was to remove the inbound-mail-parser and contact-importer out of the main SDK and allow for expansion of the SDK without bloating the core.

In your case, you might want to use a module like [request](https://github.com/request/request) or some other light weight HTTP client and build your payload directly according to [this documentation](https://sendgrid.com/docs/API_Reference/api_v3.html).

I hope that helps!

Also, if you have some ideas on how we can make our documentation language better, please let us know or if you like, we do accept PRs :)

With Best Regards,

Elmer

**Comment by SOSANA** [comment]
sorry to crash this thread but curious is the install ```npm i -S sendgrid``` still being used? has this been depreciated? If not where can I find more info about the pkg? not using the new pkg's listed above.

**Comment by thinkingserious** [comment]
Hello @SOSANA,

Yes, that version of this SDK is deprecated. [Please see here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/README.md) for the latest install instructions.

Thanks!

With Best Regards,

Elmer
