### ISSUE TITLE
My account got suspended

### ISSUE THREAD

**Issue by Nisthar** [sendgrid/sendgrid-nodejs#714]
My account got suspended using this library. I am a developer.
I am new to email marketing. Is this due to my email list?

```js
const sgMail = require('@sendgrid/mail');
const apiKey = "key";
sgMail.setApiKey(apiKey);
const list = require('./list.json');



let emailsNotSent = [];
async function run(){
for(let i=0;i<list.accounts.length;i++){
	const fullname = list.accounts[i].fullname;
	const instagram = list.accounts[i].name;
	const email = list.accounts[i].emails[0];
	

	const body = `message`;

const msg = {
  to: `${email}`,
  from: 'info@domain.com',
  subject: 'subject',
  text: body,
  // html: body,
};
const send = await sgMail.send(msg);
console.log(`${email}`);

}

}
run();

**Comment by thinkingserious** [comment]
Hello @Nisthar,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
