### ISSUE TITLE
Deeplinks being rendered as plain text

### ISSUE THREAD

**Issue by ikiugu** [sendgrid/sendgrid-nodejs#715]
#### Issue Summary

Sengrid does not render deeplinks in emails. The links are rendered as plain text

#### Steps to Reproduce

1. Create a transactional template on the dashboard
2. Add a text/button with a href having an intent for example:
`intent://myapphere#Intent;scheme=http;package=com.app;end`
3. Send this via email and the text/button only has text. Its no longer a link

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-nodejs Version: 6.3.1
* Node.js Version: 10.5.0

**Comment by thinkingserious** [comment]
Hello @ikiugu,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
