### ISSUE TITLE
The API returns 202 but i don't receive the e-mail

### ISSUE THREAD

**Issue by AlexandreUser** [sendgrid/sendgrid-nodejs#760]
### API returns 202 but the email isn't working.

I'm using the API to send multiples e-mails, sometimes they work, sometimes they don't (Most on the Gmail)
But the result for every call is the same 202, i need something to mark the error to stop.

**Comment by thinkingserious** [comment]
Hello @AlexandreUser,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
