### ISSUE TITLE
SenderNotAuthenticatedForGroup error

### ISSUE THREAD

**Issue by xyz92** [sendgrid/sendgrid-nodejs#838]
I have an email address which includes multiple recipients. When I tried sending email, it blocked sending email:

![microsoftteams-image](https://user-images.githubusercontent.com/6519992/47946087-3d684500-dec4-11e8-8359-79ad5282b690.png)

Here is my code:

using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Threading.Tasks;

namespace Example
{
    internal class Example
    {
        private static void Main()
        {
            Execute().Wait();
        }

        static async Task Execute()
        {
            var apiKey = Environment.GetEnvironmentVariable("SENDGRID_APIKEY");
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("noreply@xyz.com", "ABC DEF");
            var subject = "Notification using SendGrid";
            var to = new EmailAddress("ddd@xyz.com", "GHI JKL"); //will change to AppReviewer/AppSubmitter
            var plainTextContent = "This is a test";
            var htmlContent = "test";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);
        }
    }
}
Here ddd@xyz.com contains 3 receipients. What am I doing wrong?

**Comment by thinkingserious** [comment]
Hello @xyz92,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
