### ISSUE TITLE
Recipient not set and thus send of email is failing

### ISSUE THREAD

**Issue by ciaoben** [sendgrid/sendgrid-nodejs#848]
I am on `sendgrid/mail@6.3.1` and using this code taken from the example:

```
    const msg = {
      to: "personanalemail@domain.com",
      from: "sender@example.org",
      text: "and easy to do anywhere, even with Node.js",
      html: "<strong>and easy to do anywhere, even with Node.js</strong>",
      subject: "uxiboard",
      templateId: "d-f43daeeaef504760851f727007e0b5d0",
      dynamic_template_data: {
        name: "Jonh",
        url: "..."
      }
    };

    sgMail
      .send(msg)
      .then(e => {
        console.log("yes");
      })
      .catch(err => {
        console.log("nooo", err.toString());
      });
```

The code print "yes", so it seems to work but on the dashboard I see that every message fails, and it seems to not have the recipient set:

<img width="968" alt="schermata 2018-11-18 alle 18 14 04" src="https://user-images.githubusercontent.com/4526061/48675820-19606100-eb5e-11e8-8133-5923a24c6c40.png">

**Comment by thinkingserious** [comment]
Hello @ciaoben,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
