### ISSUE TITLE
Images not displayed in the mail

### ISSUE THREAD

**Issue by MohitSuhane** [sendgrid/sendgrid-nodejs#871]
#### Issue Summary

Sending a mail with html that contains Images. Using base64Img(base64Img.base64Sync) to encoding image as base64. Below is my code:

```
const base64Img = require('base64-img');

// base64 for images
const img1 = base64Img.base64Sync('public/image/img1.jpeg');
const img2 = base64Img.base64Sync('public/image/img2.jpg');

const html = const html = `<html>
                <body>
                    <br/>
                    <img alt="Image 1" src=${img1} />
                    <br/>
                    <img alt="Image 1" src=${img2} />
                    <br/>
                </body>
              </html>`

            const msg = {
                to: emailId,
                from: sender,
                subject: `${saleIdentifier} ${subject}`,
                text: 'and easy to do anywhere, even with Node.js',
                html: `Hi ${userName}, ${html}`,
            };
            await sgMail.send(msg);
```
The email that is send does not display the image. It shows the alt text 'Image 1', in place of image.

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

**Comment by Berkmann18** [comment]
Have you checked if the path of the image was correct?

**Comment by thinkingserious** [comment]
Thanks for helping out @Berkmann18!

@MohitSuhane,

Please do check the path and be sure that the value of `img1` and `img2` are correct.

With Best Regards,

Elmer

**Comment by Berkmann18** [comment]
@thinkingserious No problem 😄.

**Comment by thinkingserious** [comment]
Hi @MohitSuhane,

Did you still need help on this issue?

**Comment by LessaAugusto** [comment]
Same problem here! As I'm just testing the code, i'm using http://b64.io/ to encode my images. After getting the data, i'm doing something like this:

```
<img src="data:image/svg+xml;base64,...." />
```

Everything is working just fine, I've tested the html (because I'm generating it using a template language and a markup language, to make it responsive) and it looks exactly how I wanted it to look. But when I send the email, i don't know why, the user receives it with no images. I inspected the element: the src attribute was gone, it vanished and I'm pretty sure it was there before sending the email... Any tips to solve the issue?
