### ISSUE TITLE
email not sent

### ISSUE THREAD

**Issue by oprogramador** [sendgrid/sendgrid-nodejs#966]
#### Issue Summary

Sendgrid doesn't send me any emails. I obtain 202 status from Sendgrid API. I use a correct API key which was working about a year ago. I checked the spam folder is empty.

#### Steps to Reproduce

```js
#!/usr/bin/env node

const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'uomodislesia+github@gmail.com',
  from: 'test@example.com',
  subject: 'foo bar baz',
  text: 'some text',
};
sgMail.send(msg)
  .then(response => console.log(response));
```

#### Technical details:

* @sendgrid/mail: 6.4.0
* Node.js Version: 10.16.0

**Comment by oprogramador** [comment]
btw. this doesn't send any email as well:
```
curl --request POST \
  --url https://api.sendgrid.com/v3/mail/send \
  --header "Authorization: Bearer $SENDGRID_API_KEY" \
  --header 'Content-Type: application/json' \
  --data '{"personalizations": [{"to": [{"email": "uomodislesia+github@gmail.com"}]}],"from": {"email": "test@example.com"},"subject": "Sending with SendGrid is Fun","content": [{"type": "text/plain", "value": "and easy to do anywhere, even with cURL"}]}'
```
it's from this docs https://sendgrid.com/solutions/email-api/

**Comment by smakosh** [comment]
Yeah having the same issue, thinking about switching to another provider

**Comment by oprogramador** [comment]
@smakosh 

my problem was due to a missed payment so it worked after performing payment but it's strange the response status was 202

**Comment by pvcon13** [comment]
Mine is intermittent. Sending an e-mail as a test to the same user every few minutes and some happen and some do not. Using Node.js NPM more or less standard. 

1) could this be because I am sending to the same test user repeatedly (I have not noticed this when alternate e-mails are to different recipients (but then again my feedback on those is worse)

2) is there a simple way to either
a) force a send or repeat a send based on the api request (a confirm loop)
b) send it twice or some other annoying behavior to waranty delivery

3) could this be a byproduct of using the nodejs module and if I used another method like the direct api would 
a) the method be more reliable
b) provide more accurate feedback that the message was sent

Any and all ideas welcome (for the record, everything is green light - no error messages, just failed delivery. Would validating the domain sending effect the reliability (thinking the problem is not the sending but the message getting through somewhere). This is day two of a initial period of a the free service so its not about billing.

**Comment by pvcon13** [comment]
From my tests it seems that its sensitive to HTML content

I added in the pass fail return and it NEVER sees and error and always says the message was posted fine
The only difference was a slight change in an embedded URL link text

Since the send function always says the e-mail went out fine.... should I assume that I can after sending immediately ask for the status of that e-mail and see a failure? If that works, is there a best practice for retrying that send?

**Comment by emresurmeli** [comment]
I'm having a similar issue as the emails sent through the demo implementation are intermittently being delivered. And in some cases it goes to the promotion email, not the primary inbox. Any and all info would be appreciated. Btw, I'm using a free account, which shouldn't be the cause, but just putting that out there.

**Comment by thinkingserious** [comment]
Hello @oprogramador,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
