### ISSUE TITLE
Unable to Send AMP Emails

### ISSUE THREAD

**Issue by godhoomrohit** [sendgrid/sendgrid-nodejs#976]
I am unable to send AMP emails with V3 API. Your article says we can send.(https://sendgrid.com/docs/for-developers/tracking-events/google-amp-for-email/).

Code Snippets:

```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

const msg = {
  to: 'XXX@gmail.com',
  from: 'noreply@YYY.com',
  subject: 'Twilio SendGrid',
  content: [
      {
              type: "text/x-amp-html",
              value: '<!doctype html><html amp4email><head><meta charset="utf-8"><script async src="https://cdn.ampproject.org/v0.js"></script><style amp4email-boilerplate>body{visibility:hidden}</style></head><body>Hello, AMP4EMAIL world.</body></html>'
      },
      {
          type: "text/html",
          value: "<strong>and easy to do anywhere, even with Node.js ok </strong>"
      }
  ]
};

sgMail.send(msg);
```

Any configuration changes needed?

"@sendgrid/mail": "^6.4.0"
* Node.js Version: 8.11.3

**Comment by thinkingserious** [comment]
Hello @godhoomrohit,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
