### ISSUE TITLE
Not possible to stream attachment

### ISSUE THREAD

**Issue by jasperblues** [sendgrid/sendgrid-nodejs#982]
#### Issue Summary

Attaching a fairly large document will consume a lot of memory, as it doesn't appear to be possible to stream an attachment. 

#### Steps to Reproduce

1. Read the API docs for attachments. 

*Expected:*
Allows streaming an attachment. 

*Actual:*
Only a base64 encoded string can be attached. 

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

**Comment by thinkingserious** [comment]
Hello @jasperblues,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
