### ISSUE TITLE
Unable to Instantiate a new Client class

### ISSUE THREAD

**Issue by danhlee329** [sendgrid/sendgrid-nodejs#986]
#### Issue Summary

Currently I'm able to [manually create client instances](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/client#instantiate-client-instances-manually) in javascript, but am not able to do so in Typescript.

#### Steps to Reproduce

```
import { Client } from '@sendgrid/client';
const clientInstance = new Client();
```
Error : Cannot use 'new' with an expression whose type lacks a call or construct signature.

#### Technical details:
- `@sendgrid/client` Version: 6.4.0
- `Node.js` Version: 10.16.3

**Comment by dfcowell** [comment]
Also encountering this issue. Very frustrating for Typescript users.

**Comment by manusis** [comment]
We also need support for creating new instance of SendGrid/Mail fo a new API key. In Nodejs modules are singleton objects, so setApiKey would not work as it would cause race around conditions when multiple API keys are used.

**Comment by mgummelt** [comment]
I just ran into this problem as well.  Would be great to get a fix.  I'm pretty sure the problem is that this line: https://github.com/sendgrid/sendgrid-nodejs/blob/4cfbba40bf63142605d53fac7c8409894a8fbee1/packages/client/src/client.d.ts#L37

Should instead read:

`declare const client: Client & { Client: typeof Client }`

**Comment by childish-sambino** [comment]
PR submitted to fix this.
